kubernetes:
  centos:
    k8s_repo: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    k8s_repo_key: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    k8s_packages:
      - kubelet{{ '-1.24.16-0' if vars["k8s"]["cluster_version"] == '1.24' else '-1.25.12-0' if vars["k8s"]["cluster_version"] == '1.25' else '-1.26.9-0' if vars["k8s"]["cluster_version"] == '1.26' else '' }}
      - kubeadm{{ '-1.24.16-0' if vars["k8s"]["cluster_version"] == '1.24' else '-1.25.12-0' if vars["k8s"]["cluster_version"] == '1.25' else '-1.26.9-0' if vars["k8s"]["cluster_version"] == '1.26' else '' }}
      - kubectl{{ '-1.24.16-0' if vars["k8s"]["cluster_version"] == '1.24' else '-1.25.12-0' if vars["k8s"]["cluster_version"] == '1.25' else '-1.26.9-0' if vars["k8s"]["cluster_version"] == '1.26' else '' }}

  ubuntu:
    k8s_repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    k8s_repo_file: /etc/apt/sources.list.d/kubernetes.list
    k8s_repo_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    k8s_packages:
      - kubelet{{ '=1.24.16-00' if vars["k8s"]["cluster_version"] == '1.24' else '=1.25.12-00' if vars["k8s"]["cluster_version"] == '1.25' else '=1.26.9-00' if vars["k8s"]["cluster_version"] == '1.26' else '' }}
      - kubeadm{{ '=1.24.16-00' if vars["k8s"]["cluster_version"] == '1.24' else '=1.25.12-00' if vars["k8s"]["cluster_version"] == '1.25' else '=1.26.9-00' if vars["k8s"]["cluster_version"] == '1.26' else '' }}
      - kubectl{{ '=1.24.16-00' if vars["k8s"]["cluster_version"] == '1.24' else '=1.25.12-00' if vars["k8s"]["cluster_version"] == '1.25' else '=1.26.9-00' if vars["k8s"]["cluster_version"] == '1.26' else '' }}

crio:
  ubuntu:
    libcontainers_repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /
    libcontainers_key: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
    libcontainers_keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg
    crio_repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ vars["k8s"]["cluster_version"] }}/xUbuntu_22.04/ /
    crio_key: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:/{{ vars["k8s"]["cluster_version"] }}/xUbuntu_22.04/Release.key
    crio_keyring: /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg
  centos:
    libcontainers_repo: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    crio_repo: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ vars["k8s"]["cluster_version"] }}/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:{{ vars["k8s"]["cluster_version"] }}.repo
containerd:
  centos:
    containerd_repo: https://download.docker.com/linux/centos/docker-ce.repo
  ubuntu:
    containerd_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    containerd_repo_key: https://download.docker.com/linux/ubuntu/gpg
    containerd_repo_key_file: /etc/apt/trusted.gpg.d/docker.gpg
