##################################
##        Infra related         ##
##################################
workspace_directory:
  base_path: "{{ home_dir }}/k8s-setup"

terraform_url: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
image_name: OS-GenericCloud
centos:
  cloud_image: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-latest.x86_64.qcow2
ubuntu_jammy:
  cloud_image: https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img

libvirt:
  storage:
    pool_path: /media/yalim-cloud-lv1 #default is /var/lib/libvirt/images

python_packages:
  - PyYAML
  - kubernetes
  - jsonpatch
  - netaddr

os_packages:
  centos:
    - unzip
    - git
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - python3-pip
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager

  ubuntu:
    - unzip
    - git
    - gcc
    - make
    - network-manager
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - python3-pip
    - libvirt-daemon-system
    - libvirt-clients
    - libvirt-dev
    - bridge-utils
    - qemu-kvm
    - genisoimage
    - virtinst
    - virt-manager

  fedora:
    - unzip
    - git
    - gcc
    - make
    - python3-lxml
    - python3-netaddr
    - python3-libvirt
    - python3-pip
    - libvirt-devel
    - libvirt
    - qemu-kvm
    - virt-install
    - virt-manager

##################################
##      Kubernetes related      ##
##################################

cni_plugins:
  calico:
    calico_operator: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
    calico_crd: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
  flannel:
    flannel_repo: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  cilium:
    chart:
      name: cilium
      ref: cilium/cilium
      url: https://helm.cilium.io/

ingress:
  nginx:
    chart:
      name: ingress-nginx
      url: https://kubernetes.github.io/ingress-nginx
      ref: ingress-nginx/ingress-nginx
  contour:
    chart:
      name: bitnami
      url: https://charts.bitnami.com/bitnami
      ref: bitnami/contour
  haproxy:
    chart:
      name: haproxytech
      url: https://haproxytech.github.io/helm-charts
      ref: haproxytech/kubernetes-ingress

helm:
  helm_installer: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz

rook:
  operator:
    chart:
      name: rook-release
      url: https://charts.rook.io/release
      ref: rook-release/rook-ceph
  cluster:
    chart:
      name: rook-release
      url: https://charts.rook.io/release
      ref: rook-release/rook-ceph-cluster

metallb_setup:
  manifest_url: https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests
